on: [workflow_call]

permissions:
    contents: read

env:
  DENO_VERSION: "1.42"
  DENO_DIR: /home/runner/.deno-cache
  SQLITE_DATABASE_LOCATION: ":memory:"
  COOKIE_HOSTNAME: localhost
  SERVER_ADDRESS: 0.0.0.0
  COOKIE_SECURE: 1
  COOKIE_MAX_AGE_SECONDS: 43200
  DISABLE_SERVICE_PERIODIC_TASKS: 0
  WEBSOCKET_PORT: 8080
  WEBSERVER_PORT: 8000
  LOGGING_LEVEL: INFO
  SHOW_LOG_COLORS: 1
  DISABLE_SERVICE_WEBSOCKET: 0
  RUN_MIGRATIONS_ON_STARTUP: 0


jobs:
    run-check:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                ref: ${{ github.ref }}

            - uses: denoland/setup-deno@v1
              with:
                deno-version: v1.42

            - name: Cache Deno dependencies 
              uses: actions/cache@v3
              with:
                path: ${{ env.DENO_DIR }}
                key: ${{ hashFiles('deno.lock') }}

            - name: Run checks and tests
              run: |
                set -e
                deno task check
                deno task test