on: [workflow_call]

permissions:
    contents: read

env:
  DENO_VERSION: "1.41.3"
  DENO_DIR: ~/.deno-cache

jobs:
    run-check:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - uses: denoland/setup-deno@v1
              with:
                deno-version: v1.41.3

            - name: Cache Deno dependencies 
              uses: actions/cache@v3
              with:
                path: ${{ env.DENO_DIR }}
                key: ${{ hashFiles('deno.lock') }}

            - name: Run checks and tests
              run: |
                set -e
                deno task check
                deno task test